# Generated by Django 4.1.3 on 2022-11-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movie_delete_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='xyz', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
